drop table if exists member cascade;
drop table if exists source cascade;
drop table if exists subscription cascade;

create table member (
    creation_timestamp timestamp(6),
    member_id bigint generated by default as identity,
    update_timestamp timestamp(6),
    email varchar(255),
    name varchar(255),
    primary key (member_id)
);

create table source (
    creation_timestamp timestamp(6),
    source_id bigint generated by default as identity,
    update_timestamp timestamp(6),
    description varchar(255),
    name varchar(255),
    url varchar(255),
    primary key (source_id)
);

create table subscription (
    creation_timestamp timestamp(6),
    member_id bigint,
    source_id bigint,
    subscription_id bigint generated by default as identity,
    primary key (subscription_id)
);