create table Member (
    creationTimestamp timestamp(6),
    member_id bigint generated by default as identity,
    updateTimestamp timestamp(6),
    email varchar(255),
    name varchar(255),
    primary key (member_id)
);

create table Source (
    creationTimestamp timestamp(6),
    source_id bigint generated by default as identity,
    updateTimestamp timestamp(6),
    name varchar(255),
    url varchar(255),
    primary key (source_id)
);

create table Subscription (
  creationTimestamp timestamp(6),
  member_id bigint,
  source_id bigint,
  subscription_id bigint generated by default as identity,
  primary key (subscription_id)
);