# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Manual CI/CD

on:
  workflow_dispatch
  
permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Run chmod to make gradlew executable
      run: chmod +x ./gradlew
    - name: Build with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: build
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: cicd
        path: build/libs/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: cicd
      - name: ssh Reset
        uses: ssh-keygen -R ${{ secrets.SERVER_DOMAIN_NAME }}
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: SCP transfer
        run: scp *.jar ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_DOMAIN_NAME }}:~/cicd
      - name: Execute remote commands
        run: |
          ssh ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_DOMAIN_NAME }} "sudo fuser -k 8080/tcp"
          ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_DOMAIN_NAME }} "sudo nohup java -jar ~/cicd/*.jar &"
